version: "3.9"

services:
  db:
    image: postgres:16
    container_name: odoo19-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 10

  odoo:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: odoo19

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8069:8069"
      - "8072:8072"

    environment:
      DB_HOST: aj2bw2o3sd2bt46ogq2b7jfk
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: lw2dxkJGaQG9oPHRoiIXozNeDAvUfn3JwHbVQG2MnOKtxw3YGwngOZ9K1smh31KK

    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/custom-addons

volumes:
  postgres_data:
  odoo_data:
