[options]

admin_passwd = admin

db_host = aj2bw2o3sd2bt460gq2b7jfk
db_port = 5432
db_user = postgres
db_password = lw2dxkJGaQG9oPHRoiIXozNeDAvUfn3JwHbVQG2MnOKtxw3YGwngOZ9K1smh31KK

addons_path =
    /opt/odoo/addons,
    /opt/enterprise,
    /mnt/custom-addons

data_dir = /var/lib/odoo

proxy_mode = True

workers = 4

max_cron_threads = 2

limit_time_cpu = 600
limit_time_real = 1200

longpolling_port = 8072

log_level = info
