[options]

admin_passwd = admin

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

addons_path =
    /opt/odoo/addons,
    /opt/enterprise,
    /mnt/custom-addons

data_dir = /var/lib/odoo

proxy_mode = True

workers = 4

max_cron_threads = 2

limit_time_cpu = 600
limit_time_real = 1200

longpolling_port = 8072

log_level = info
